Helm 3 support.
gmorse81/boondoggle pull request #23
Opened 2020-10-02 15:02 UTC by gmorse81

Also removes git cloning support since it never really worked right anyways.

2020-10-02 18:58 UTC, johnhoodjr requested changes

2020-10-02 18:58 UTC, johnhoodjr commented on boondoggle/reqbuild.go
> +// WriteRequirements writes the dependencies to eithe chart.yaml or requirements.yaml depending on the version of helm you are running
```suggestion
// WriteRequirements writes the dependencies to either chart.yaml or requirements.yaml depending on the version of helm you are running
```

2020-10-02 18:58 UTC, johnhoodjr commented on cmd/up.go
> +		// Write the new requirements.yml or chart.yaml
```suggestion
		// Write the new requirements.yaml or chart.yaml
```

2020-10-02 19:43 UTC, johnhoodjr approved these changes

2020-10-02 20:07 UTC, codycraven commented on boondoggle/helm.go
> +	chunk := "--timeout 1800s --wait"
Verify helm 2 works with quantifier.

2020-10-05 12:38 UTC, johnhoodjr requested changes

2020-10-05 12:38 UTC, johnhoodjr commented on boondoggle/helm.go
> +	fmt.Println(b.HelmVersion)
```suggestion
```

2020-10-05 14:29 UTC, merged